/**
 * Brawlify API (not official)
 * Some queries of the Brawlify API. This content is not affiliated with, endorsed, sponsored, or specifically approved by Supercell nor Brawlify and Supercell or Brawlify are not responsible for it
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';


import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class MapService {

    protected basePath = 'https://api.brawlapi.com/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Finds all maps
     * All maps
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllMaps(observe?: 'body', reportProgress?: boolean): Observable<Array<any>>;
    public getAllMaps(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<any>>>;
    public getAllMaps(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<any>>>;
    public getAllMaps(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<any>>(`${this.basePath}/maps`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Finds a map based on map ID
     * A map information
     * @param mapId ID of map to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getMap(mapId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getMap(mapId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getMap(mapId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getMap(mapId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (mapId === null || mapId === undefined) {
            throw new Error('Required parameter mapId was null or undefined when calling getMap.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/maps/${encodeURIComponent(String(mapId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Finds a map based on map ID with custom stats
     * A map information, with the stats of the trophy range
     * @param mapId ID of map to return
     * @param trophyRange Trophy Range of which return the stats
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getMapWithTrophyRange(mapId: number, trophyRange: '0-299' | '300-599' | '600+', observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getMapWithTrophyRange(mapId: number, trophyRange: '0-299' | '300-599' | '600+', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getMapWithTrophyRange(mapId: number, trophyRange: '0-299' | '300-599' | '600+', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getMapWithTrophyRange(mapId: number, trophyRange: '0-299' | '300-599' | '600+', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (mapId === null || mapId === undefined) {
            throw new Error('Required parameter mapId was null or undefined when calling getMapWithTrophyRange.');
        }

        if (trophyRange === null || trophyRange === undefined) {
            throw new Error('Required parameter trophyRange was null or undefined when calling getMapWithTrophyRange.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/maps/${encodeURIComponent(String(mapId))}/${encodeURIComponent(String(trophyRange))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
