/**
 * Brawlify API (not official)
 * Some queries of the Brawlify API. This content is not affiliated with, endorsed, sponsored, or specifically approved by Supercell nor Brawlify and Supercell or Brawlify are not responsible for it
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Environment } from './environment';
import { GameModeRef } from './gameModeRef';
import { Stat } from './stat';
import { TeamStat } from './teamStat';


export interface ModelMap { 
    id: number;
    _new: boolean;
    disabled: boolean;
    name: string;
    hash: string;
    version: number;
    link: string;
    imageUrl: string;
    credit?: string;
    environment: Environment;
    gameMode: GameModeRef;
    lastActive: number;
    dataUpdated: number;
    /**
     * Only present when obtaining the map alone, not with a group
     */
    stats?: Array<Stat>;
    /**
     * Only present when obtaining the map alone, not with a group
     */
    teamStats?: Array<TeamStat>;
}
